In [75]:
import os
import pandas as pd
import random
import numpy as np


def AP(a,d,n): 

    # Printing AP by simply adding d 
    # to previous term. 
    curr_term = a 
    ap = []

    for i in range(1,n+1): 
        ap.append(curr_term)
        curr_term =curr_term + d 
    
    return ap
           

def generate_data(tatal_sample, num_obs_min,num_obs_max, slope_min_range, slope_max_range,std):
    observations = {}
    oberserved_data = []
    target = []
    for per_example in range(tatal_sample):
        
        n = random.randrange(num_obs_min,num_obs_max)
        target_number = n+1
        std = std
#         slope = random.randrange(slope_min_range,slope_max_range)
#         slope1 =  random.randrange(slope_min_range,slope_max_range)
#         b = np.random.randn(target_number)*std
        
        x_intial_number = random.randrange(2,200)
        y_initial_number = random.randrange(2,200)
        z_initial_number = random.randrange(2,200)
        x_diff = random.randrange(2,10)
        y_diff = random.randrange(2,10)
        z_diff = random.randrange(2,10)
        x = AP(x_intial_number,x_diff,target_number)
        y = AP(y_initial_number,y_diff,target_number)
        z = AP(z_initial_number,z_diff,target_number)
        print(x_diff)
        print(y_diff)
        print(z_diff)
        sort_type = random.choice([1,2])
#         sort_type = 1
#         print(sort_type)
        if sort_type == 1:
            pass
        else:
            x = x[::-1]
            y = y[::-1]
            z = z[::-1]
        oberserved_data.append([[x[i],y[i],z[i]] for i in range(n)])
        target.append([[x[i],y[i],z[i]] for i in range(n,target_number)])
    observations['fly_position'] = oberserved_data
    observations['target'] = target
    data = pd.DataFrame(observations)
    data.to_csv(os.getcwd()+"/fly_position.csv")
    return oberserved_data,target

In [76]:
data_final,observations = generate_data(100,10,15,10,20,50)

7
6
3
4
6
9
2
4
4
9
6
4
8
6
4
2
6
6
7
6
7
5
5
6
8
3
6
9
4
4
4
7
2
8
3
2
6
4
3
3
6
9
5
9
9
2
7
5
7
2
3
5
6
6
5
7
6
8
8
4
9
9
4
4
2
7
4
8
3
2
6
5
6
7
2
3
6
4
6
5
4
3
3
5
9
7
8
6
6
2
2
7
6
5
5
9
3
3
6
8
5
9
2
5
5
3
7
3
5
3
8
3
3
7
3
5
8
6
2
2
5
8
7
5
6
2
3
3
5
3
4
4
3
3
6
2
4
2
5
7
3
2
9
4
2
2
9
5
5
7
3
7
4
7
7
5
4
6
5
9
8
3
2
7
8
7
5
3
6
6
7
7
6
9
7
5
5
4
5
9
7
3
7
4
2
3
6
9
6
9
6
3
5
9
5
2
8
3
6
3
6
8
6
6
9
4
3
6
9
6
7
3
3
3
7
6
5
2
9
9
4
4
9
9
9
6
9
3
3
6
9
3
6
8
6
3
4
7
4
7
4
6
7
7
8
7
5
8
7
6
6
5
6
3
5
9
5
4
6
4
2
9
4
5
5
6
6
2
5
6
2
4
6
5
8
6
4
7
9
6
2
7
2
2
2
7
6
2
7
7
2
4
7
9
7
5
3
5
2
4


In [68]:
import keras
X_new = keras.preprocessing.sequence.pad_sequences(data_final,maxlen=15)

In [69]:
X = np.array(X_new)
y = np.array(observations)

In [70]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
num_instances, num_time_steps, num_features = X.shape
x_new = np.reshape(X,(-1, num_features))
x_new = scaler.fit_transform(x_new)
x_new = np.reshape(x_new, (num_instances, num_time_steps, num_features))

num_instances, num_time_steps, num_features = y.shape
y_new = np.reshape(y,(-1, num_features))
y_new = scaler.fit_transform(y_new)
y_new = np.reshape(y_new, (num_instances, num_time_steps, num_features))

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_new, y_new, test_size=0.30, random_state=42)

In [72]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Masking
from keras.layers import SimpleRNN
from keras.layers import RepeatVector
from keras.layers import TimeDistributed




n_features = 3
n_steps_in, n_steps_out = 15, 1


model = Sequential()
model.add(SimpleRNN(200, activation='relu', input_shape=(n_steps_in, n_features)))
model.add(RepeatVector(n_steps_out))
model.add(SimpleRNN(200, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
model.compile(optimizer='adam', loss='mean_squared_error')


model.fit(X_train, y_train, epochs=500)

Epoch 1/500
70/70 [==============================] - 1s 7ms/step - loss: 0.1422
Epoch 2/500
70/70 [==============================] - 0s 249us/step - loss: 0.0412
Epoch 3/500
70/70 [==============================] - 0s 257us/step - loss: 0.0275
Epoch 4/500
70/70 [==============================] - 0s 235us/step - loss: 0.0214
Epoch 5/500
70/70 [==============================] - 0s 247us/step - loss: 0.0152
Epoch 6/500
70/70 [==============================] - 0s 264us/step - loss: 0.0084
Epoch 7/500
70/70 [==============================] - 0s 265us/step - loss: 0.0056
Epoch 8/500
70/70 [==============================] - 0s 234us/step - loss: 0.0046
Epoch 9/500
70/70 [==============================] - 0s 263us/step - loss: 0.0029
Epoch 10/500
70/70 [==============================] - 0s 255us/step - loss: 0.0026
Epoch 11/500
70/70 [==============================] - 0s 252us/step - loss: 0.0017
Epoch 12/500
70/70 [==============================] - 0s 261us/step - loss: 0.0015
Epoch 13/500
70

Epoch 96/500
70/70 [==============================] - 0s 246us/step - loss: 3.7739e-05
Epoch 97/500
70/70 [==============================] - 0s 239us/step - loss: 4.3732e-05
Epoch 98/500
70/70 [==============================] - 0s 237us/step - loss: 3.1508e-05
Epoch 99/500
70/70 [==============================] - 0s 241us/step - loss: 4.3190e-05
Epoch 100/500
70/70 [==============================] - 0s 235us/step - loss: 3.3282e-05
Epoch 101/500
70/70 [==============================] - 0s 235us/step - loss: 3.3845e-05
Epoch 102/500
70/70 [==============================] - 0s 237us/step - loss: 3.1973e-05
Epoch 103/500
70/70 [==============================] - 0s 233us/step - loss: 2.9042e-05
Epoch 104/500
70/70 [==============================] - 0s 239us/step - loss: 2.5024e-05
Epoch 105/500
70/70 [==============================] - 0s 228us/step - loss: 3.1512e-05
Epoch 106/500
70/70 [==============================] - 0s 253us/step - loss: 2.6652e-05
Epoch 107/500
70/70 [===============

70/70 [==============================] - 0s 229us/step - loss: 8.2184e-06
Epoch 190/500
70/70 [==============================] - 0s 224us/step - loss: 1.2323e-05
Epoch 191/500
70/70 [==============================] - 0s 236us/step - loss: 1.7928e-05
Epoch 192/500
70/70 [==============================] - 0s 227us/step - loss: 1.0227e-05
Epoch 193/500
70/70 [==============================] - 0s 234us/step - loss: 2.0107e-05
Epoch 194/500
70/70 [==============================] - 0s 229us/step - loss: 2.1094e-05
Epoch 195/500
70/70 [==============================] - 0s 225us/step - loss: 4.5395e-05
Epoch 196/500
70/70 [==============================] - 0s 232us/step - loss: 5.1370e-05
Epoch 197/500
70/70 [==============================] - 0s 229us/step - loss: 4.2759e-05
Epoch 198/500
70/70 [==============================] - 0s 244us/step - loss: 2.9139e-05
Epoch 199/500
70/70 [==============================] - 0s 271us/step - loss: 2.8784e-05
Epoch 200/500
70/70 [=========================

70/70 [==============================] - 0s 235us/step - loss: 2.2400e-05
Epoch 283/500
70/70 [==============================] - 0s 229us/step - loss: 1.1699e-05
Epoch 284/500
70/70 [==============================] - 0s 235us/step - loss: 1.2560e-05
Epoch 285/500
70/70 [==============================] - 0s 230us/step - loss: 1.0626e-05
Epoch 286/500
70/70 [==============================] - 0s 229us/step - loss: 1.3380e-05
Epoch 287/500
70/70 [==============================] - 0s 224us/step - loss: 1.2491e-05
Epoch 288/500
70/70 [==============================] - 0s 230us/step - loss: 1.2765e-05
Epoch 289/500
70/70 [==============================] - 0s 232us/step - loss: 8.3002e-06
Epoch 290/500
70/70 [==============================] - 0s 229us/step - loss: 7.7728e-06
Epoch 291/500
70/70 [==============================] - 0s 226us/step - loss: 8.7678e-06
Epoch 292/500
70/70 [==============================] - 0s 240us/step - loss: 7.2699e-06
Epoch 293/500
70/70 [=========================

Epoch 375/500
70/70 [==============================] - 0s 236us/step - loss: 1.5351e-05
Epoch 376/500
70/70 [==============================] - 0s 235us/step - loss: 1.5737e-05
Epoch 377/500
70/70 [==============================] - 0s 230us/step - loss: 1.6132e-05
Epoch 378/500
70/70 [==============================] - 0s 232us/step - loss: 3.2127e-05
Epoch 379/500
70/70 [==============================] - 0s 260us/step - loss: 4.3392e-05
Epoch 380/500
70/70 [==============================] - 0s 263us/step - loss: 2.5492e-05
Epoch 381/500
70/70 [==============================] - 0s 233us/step - loss: 2.3158e-05
Epoch 382/500
70/70 [==============================] - 0s 226us/step - loss: 2.2300e-05
Epoch 383/500
70/70 [==============================] - 0s 225us/step - loss: 2.1203e-05
Epoch 384/500
70/70 [==============================] - 0s 230us/step - loss: 2.0334e-05
Epoch 385/500
70/70 [==============================] - 0s 230us/step - loss: 2.3520e-05
Epoch 386/500
70/70 [===========

70/70 [==============================] - 0s 228us/step - loss: 1.6134e-05
Epoch 469/500
70/70 [==============================] - 0s 231us/step - loss: 1.1669e-05
Epoch 470/500
70/70 [==============================] - 0s 234us/step - loss: 2.1188e-05
Epoch 471/500
70/70 [==============================] - 0s 233us/step - loss: 1.8677e-05
Epoch 472/500
70/70 [==============================] - 0s 229us/step - loss: 2.3166e-05
Epoch 473/500
70/70 [==============================] - 0s 224us/step - loss: 2.6904e-05
Epoch 474/500
70/70 [==============================] - 0s 228us/step - loss: 3.2509e-05
Epoch 475/500
70/70 [==============================] - 0s 229us/step - loss: 2.6593e-05
Epoch 476/500
70/70 [==============================] - 0s 235us/step - loss: 2.7476e-05
Epoch 477/500
70/70 [==============================] - 0s 233us/step - loss: 1.8421e-05
Epoch 478/500
70/70 [==============================] - 0s 231us/step - loss: 1.0627e-05
Epoch 479/500
70/70 [=========================

In [99]:
y_new = scaler.fit_transform([[  100,   1,   1],
       [  95,   1,   1],
       [ 90,   1,   1],
       [ 85,   1,   1],
       [ 80,   1,   1],
       [ 75,   1,   1],
       [ 70,   1,   1],
       [ 65,   1,   1],
       [ 60,   1,   1],
       [ 55,   1,   1],
       [ 50,   1,   1],
       [ 45,   1,   1],
       [ 40,   1,   1],
       [ 35,   1,   1],
       [ 30,   1,   1]])

In [104]:
from numpy import array
# input = keras.preprocessing.sequence.pad_sequences([[  16.45804213,   15.22674803,  421.3679909 ],
#        [  25.69521551,   15.59178985,  485.91398398],
#        [  32.85040243,   32.69030608,  981.69952713],
#        [  38.50750021,   40.35122778, 1027.83537699],
#        [  49.15993022,   42.1613794 , 1342.69331204],
#        [  61.35052901,   43.00845395, 1561.06022516],
#        [  62.38931938,   61.20173446, 1818.21389825],
#        [  70.11458945,   61.88013684, 1899.76126092],
#        [  74.57335295,   77.42281882, 2094.50162743],
#        [  75.44818747,   77.98237104, 2250.63550946]], maxlen=20)

n_steps = 15
n_features = 3

x_input = array([y_new])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input)


# for i in range(5):
#     if i ==0:
#         yhat = model.predict(x_input)
#         c = 
#         print(yhat)
#         c = yhat
#     else:
#         yhat = model.predict(c)
#         print(yhat)
#         c = yhat
        
        
print(yhat)
out = np.reshape(yhat,(-1, 3))
out = scaler.inverse_transform(out)
out = np.reshape(out, (1, 1, 3))

out

[[[0.02919925 0.02966366 0.00061878]]]


array([[[32.04395  ,  1.0296637,  1.0006188]]], dtype=float32)

In [80]:
y_new.pop(0).append([0.02919925,0.02966366,0.00061878])

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [84]:
np.delete(y_new,0).append([0.02919925,0.02966366,0.00061878])

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [87]:
np.append(y_new,[0.02919925,0.02966366,0.00061878])

array([1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.28571429e-01,
       0.00000000e+00, 0.00000000e+00, 8.57142857e-01, 0.00000000e+00,
       0.00000000e+00, 7.85714286e-01, 0.00000000e+00, 0.00000000e+00,
       7.14285714e-01, 0.00000000e+00, 0.00000000e+00, 6.42857143e-01,
       0.00000000e+00, 0.00000000e+00, 5.71428571e-01, 0.00000000e+00,
       0.00000000e+00, 5.00000000e-01, 0.00000000e+00, 0.00000000e+00,
       4.28571429e-01, 0.00000000e+00, 0.00000000e+00, 3.57142857e-01,
       0.00000000e+00, 0.00000000e+00, 2.85714286e-01, 0.00000000e+00,
       0.00000000e+00, 2.14285714e-01, 0.00000000e+00, 0.00000000e+00,
       1.42857143e-01, 0.00000000e+00, 0.00000000e+00, 7.14285714e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.91992500e-02, 2.96636600e-02, 6.18780000e-04])

In [91]:
array(y_new.tolist().pop(0).append([0.02919925,0.02966366,0.00061878]))

array(None, dtype=object)

In [96]:
y = y_new.tolist()[1:]

In [97]:
y.append([0.02919925,0.02966366,0.00061878])

In [98]:
y

[[0.9285714285714286, 0.0, 0.0],
 [0.857142857142857, 0.0, 0.0],
 [0.7857142857142856, 0.0, 0.0],
 [0.7142857142857142, 0.0, 0.0],
 [0.6428571428571428, 0.0, 0.0],
 [0.5714285714285714, 0.0, 0.0],
 [0.49999999999999994, 0.0, 0.0],
 [0.42857142857142855, 0.0, 0.0],
 [0.35714285714285715, 0.0, 0.0],
 [0.28571428571428575, 0.0, 0.0],
 [0.21428571428571425, 0.0, 0.0],
 [0.14285714285714285, 0.0, 0.0],
 [0.07142857142857145, 0.0, 0.0],
 [0.0, 0.0, 0.0],
 [0.02919925, 0.02966366, 0.00061878]]

In [100]:
y_new

array([[1.        , 0.        , 0.        ],
       [0.92857143, 0.        , 0.        ],
       [0.85714286, 0.        , 0.        ],
       [0.78571429, 0.        , 0.        ],
       [0.71428571, 0.        , 0.        ],
       [0.64285714, 0.        , 0.        ],
       [0.57142857, 0.        , 0.        ],
       [0.5       , 0.        , 0.        ],
       [0.42857143, 0.        , 0.        ],
       [0.35714286, 0.        , 0.        ],
       [0.28571429, 0.        , 0.        ],
       [0.21428571, 0.        , 0.        ],
       [0.14285714, 0.        , 0.        ],
       [0.07142857, 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [101]:
x_input = array([y_new])
x_input = x_input.reshape((1, n_steps, n_features))

In [102]:
x_input

array([[[1.        , 0.        , 0.        ],
        [0.92857143, 0.        , 0.        ],
        [0.85714286, 0.        , 0.        ],
        [0.78571429, 0.        , 0.        ],
        [0.71428571, 0.        , 0.        ],
        [0.64285714, 0.        , 0.        ],
        [0.57142857, 0.        , 0.        ],
        [0.5       , 0.        , 0.        ],
        [0.42857143, 0.        , 0.        ],
        [0.35714286, 0.        , 0.        ],
        [0.28571429, 0.        , 0.        ],
        [0.21428571, 0.        , 0.        ],
        [0.14285714, 0.        , 0.        ],
        [0.07142857, 0.        , 0.        ],
        [0.        , 0.        , 0.        ]]])