In [503]:
import os
import pandas as pd
import random
import numpy as np
def generate_data(tatal_sample, num_obs_min,num_obs_max, slope_min_range, slope_max_range,std):
    observations = {}
    oberserved_data = []
    target = []
    for per_example in range(tatal_sample):
        
        n = random.randrange(num_obs_min,num_obs_max)
        target_number = n+5
        std = std
        slope = random.randrange(slope_min_range,slope_max_range)
        slope1 =  random.randrange(slope_min_range,slope_max_range)
        b = np.random.randn(target_number)*std
        
#         sort_type = random.choice([1,2])
        sort_type = 1
        print(sort_type)
        if sort_type == 1:
        # Data Generation
            x = np.sort(np.random.uniform(0, 100, target_number))
            y = np.sort(np.random.uniform(0, 100, target_number))
            z = np.sort(b + slope* x + slope1 * y)
        else:
            x = np.sort(np.random.uniform(0, 100, target_number))[::-1]
            y = np.sort(np.random.uniform(0, 100, target_number))[::-1]
            z = np.sort(b + slope* x + slope1 * y)[::-1]
        oberserved_data.append([[x[i],y[i],z[i]] for i in range(n)])
        target.append([[x[i],y[i],z[i]] for i in range(n,target_number)])
    observations['fly_position'] = oberserved_data
    observations['target'] = target
    data = pd.DataFrame(observations)
    data.to_csv(os.getcwd()+"/fly_position.csv")
    return oberserved_data,target

In [504]:
data_final,observations = generate_data(10000,10,15,10,20,50)

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1


In [475]:
import os
def generate_data(tatal_sample, num_obs_min,num_obs_max, slope_min_range, slope_max_range,std):
    observations = {}
    oberserved_data = []
    target = []
    for per_example in range(tatal_sample):
        
        n = 10
        target_number = n+1
        std = std
        slope = random.randrange(slope_min_range,slope_max_range)
        slope1 =  random.randrange(slope_min_range,slope_max_range)
        b = np.random.randn(target_number)*std
        
        # Data Generation
        x = np.sort(np.random.uniform(0, 100, target_number))
        y = np.sort(np.random.uniform(0, 100, target_number))
        z = np.sort(b + slope* x + slope1 * y)
        oberserved_data.append([[x[i],y[i],z[i]] for i in range(n)])
        target.append([[x[i],y[i],z[i]] for i in range(n,target_number)])
    observations['fly_position'] = oberserved_data
    observations['target'] = target
    data = pd.DataFrame(observations)
    data.to_csv(os.getcwd()+"/fly_position.csv")
    return oberserved_data,target

In [542]:
import keras
X_new = keras.preprocessing.sequence.pad_sequences(data_final,maxlen=15)

In [543]:
# y_new = []
# # 
# for i in observations:
#     y_new.append(i[0])

In [544]:
X = np.array(X_new)
y = np.array(observations)

In [545]:
y.shape

(1000, 5, 3)

In [572]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
num_instances, num_time_steps, num_features = X.shape
x_new = np.reshape(X,(-1, num_features))
x_new = scaler.fit_transform(x_new)
x_new = np.reshape(x_new, (num_instances, num_time_steps, num_features))

In [573]:
num_instances, num_time_steps, num_features = y.shape
y_new = np.reshape(y,(-1, num_features))
y_new = scaler.fit_transform(y_new)
y_new = np.reshape(y_new, (num_instances, num_time_steps, num_features))

In [574]:
# y_new = scaler.fit_transform(y)

In [575]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_new, y_new, test_size=0.30, random_state=42)

In [550]:
# from keras.models import Sequential
# from keras.layers import LSTM
# from keras.layers import Dense
# from keras.layers import Masking



# # n_steps = 15

# # n_features = 3

# # model = Sequential()
# # model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
# # model.add(LSTM(100, activation='relu'))
# # model.add(Dense(3))
# # model.add(Reshape((10, 2)))
# # model.compile(optimizer='adam', loss='mean_squared_error')

# n_features = 3
# n_steps_in, n_steps_out = 15, 5

# model = Sequential()
# model.add(LSTM(200, activation='relu', input_shape=(n_steps_in, n_features)))
# model.add(RepeatVector(n_steps_out))
# model.add(LSTM(200, activation='relu', return_sequences=True))
# model.add(TimeDistributed(Dense(n_features)))
# model.compile(optimizer='adam', loss='mean_squared_error')


# model.fit(X_train, y_train, epochs=500)

In [551]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Masking


n_features = 3
n_steps_in, n_steps_out = 15, 5
from keras.layers import SimpleRNN


model = Sequential()
model.add(SimpleRNN(200, activation='relu', input_shape=(n_steps_in, n_features)))
model.add(RepeatVector(n_steps_out))
model.add(SimpleRNN(200, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
model.compile(optimizer='adam', loss='mean_squared_error')


model.fit(X_train, y_train, epochs=500)

Epoch 1/500
700/700 [==============================] - 3s 4ms/step - loss: 0.0420
Epoch 2/500
700/700 [==============================] - 0s 262us/step - loss: 0.0049
Epoch 3/500
700/700 [==============================] - 0s 251us/step - loss: 0.0016
Epoch 4/500
700/700 [==============================] - 0s 259us/step - loss: 8.1759e-04
Epoch 5/500
700/700 [==============================] - 0s 259us/step - loss: 5.4794e-04
Epoch 6/500
700/700 [==============================] - 0s 267us/step - loss: 4.6247e-04
Epoch 7/500
700/700 [==============================] - 0s 273us/step - loss: 3.8062e-04
Epoch 8/500
700/700 [==============================] - 0s 269us/step - loss: 4.5300e-04
Epoch 9/500
700/700 [==============================] - 0s 252us/step - loss: 3.6490e-04
Epoch 10/500
700/700 [==============================] - 0s 245us/step - loss: 2.9806e-04
Epoch 11/500
700/700 [==============================] - 0s 252us/step - loss: 3.3439e-04
Epoch 12/500
700/700 [======================

700/700 [==============================] - 0s 264us/step - loss: 1.4449e-05
Epoch 94/500
700/700 [==============================] - 0s 265us/step - loss: 5.4413e-05
Epoch 95/500
700/700 [==============================] - 0s 252us/step - loss: 5.8222e-05
Epoch 96/500
700/700 [==============================] - 0s 265us/step - loss: 7.3055e-05
Epoch 97/500
700/700 [==============================] - 0s 258us/step - loss: 1.1386e-04
Epoch 98/500
700/700 [==============================] - 0s 263us/step - loss: 9.4615e-05
Epoch 99/500
700/700 [==============================] - 0s 266us/step - loss: 4.4633e-05
Epoch 100/500
700/700 [==============================] - 0s 254us/step - loss: 9.9468e-05
Epoch 101/500
700/700 [==============================] - 0s 257us/step - loss: 1.7587e-04
Epoch 102/500
700/700 [==============================] - 0s 271us/step - loss: 6.3899e-05
Epoch 103/500
700/700 [==============================] - 0s 259us/step - loss: 3.2532e-05
Epoch 104/500
700/700 [=======

700/700 [==============================] - 0s 246us/step - loss: 9.5169e-05
Epoch 185/500
700/700 [==============================] - 0s 245us/step - loss: 6.5854e-05
Epoch 186/500
700/700 [==============================] - 0s 248us/step - loss: 2.9532e-05
Epoch 187/500
700/700 [==============================] - 0s 247us/step - loss: 3.3500e-05
Epoch 188/500
700/700 [==============================] - 0s 246us/step - loss: 2.4266e-05
Epoch 189/500
700/700 [==============================] - 0s 246us/step - loss: 3.4028e-05
Epoch 190/500
700/700 [==============================] - 0s 245us/step - loss: 8.5224e-05
Epoch 191/500
700/700 [==============================] - 0s 245us/step - loss: 3.9315e-05
Epoch 192/500
700/700 [==============================] - 0s 255us/step - loss: 5.9095e-05
Epoch 193/500
700/700 [==============================] - 0s 250us/step - loss: 3.1990e-05
Epoch 194/500
700/700 [==============================] - 0s 244us/step - loss: 3.1941e-05
Epoch 195/500
700/700 [=

700/700 [==============================] - 0s 248us/step - loss: 4.0181e-05
Epoch 276/500
700/700 [==============================] - 0s 257us/step - loss: 6.4057e-05
Epoch 277/500
700/700 [==============================] - 0s 249us/step - loss: 3.3693e-05
Epoch 278/500
700/700 [==============================] - 0s 248us/step - loss: 3.2230e-05
Epoch 279/500
700/700 [==============================] - 0s 243us/step - loss: 1.9862e-05
Epoch 280/500
700/700 [==============================] - 0s 244us/step - loss: 1.9340e-05
Epoch 281/500
700/700 [==============================] - 0s 247us/step - loss: 1.3629e-05
Epoch 282/500
700/700 [==============================] - 0s 249us/step - loss: 1.2429e-05
Epoch 283/500
700/700 [==============================] - 0s 248us/step - loss: 1.6264e-05
Epoch 284/500
700/700 [==============================] - 0s 251us/step - loss: 2.8442e-05
Epoch 285/500
700/700 [==============================] - 0s 246us/step - loss: 1.3656e-05
Epoch 286/500
700/700 [=

700/700 [==============================] - 0s 246us/step - loss: 2.4087e-05
Epoch 367/500
700/700 [==============================] - 0s 254us/step - loss: 2.0647e-05
Epoch 368/500
700/700 [==============================] - 0s 273us/step - loss: 2.6084e-05
Epoch 369/500
700/700 [==============================] - 0s 256us/step - loss: 1.7673e-05
Epoch 370/500
700/700 [==============================] - 0s 247us/step - loss: 4.3464e-05
Epoch 371/500
700/700 [==============================] - 0s 247us/step - loss: 4.5155e-05
Epoch 372/500
700/700 [==============================] - 0s 254us/step - loss: 5.3130e-05
Epoch 373/500
700/700 [==============================] - 0s 246us/step - loss: 3.3720e-05
Epoch 374/500
700/700 [==============================] - 0s 253us/step - loss: 1.8484e-05
Epoch 375/500
700/700 [==============================] - 0s 245us/step - loss: 2.0729e-05
Epoch 376/500
700/700 [==============================] - 0s 244us/step - loss: 2.8720e-05
Epoch 377/500
700/700 [=

700/700 [==============================] - 0s 261us/step - loss: 1.1108e-05
Epoch 458/500
700/700 [==============================] - 0s 251us/step - loss: 8.6612e-06
Epoch 459/500
700/700 [==============================] - 0s 250us/step - loss: 2.0122e-05
Epoch 460/500
700/700 [==============================] - 0s 247us/step - loss: 2.1641e-05
Epoch 461/500
700/700 [==============================] - 0s 244us/step - loss: 1.7337e-05
Epoch 462/500
700/700 [==============================] - 0s 247us/step - loss: 1.3174e-05
Epoch 463/500
700/700 [==============================] - 0s 246us/step - loss: 1.6214e-05
Epoch 464/500
700/700 [==============================] - 0s 249us/step - loss: 1.5171e-05
Epoch 465/500
700/700 [==============================] - 0s 246us/step - loss: 3.1923e-05
Epoch 466/500
700/700 [==============================] - 0s 249us/step - loss: 4.9096e-05
Epoch 467/500
700/700 [==============================] - 0s 247us/step - loss: 6.2086e-05
Epoch 468/500
700/700 [=

In [570]:
trainPredict_final = model.predict(X_train)
testPredict_final = model.predict(X_test)

In [565]:
trainPredict_final

array([[[0.5653678 , 0.55540913, 0.4599065 ],
        [0.55003667, 0.5553692 , 0.43417272],
        [0.5374489 , 0.5495537 , 0.4088653 ],
        [0.52268267, 0.54716724, 0.38361305],
        [0.51199514, 0.54545325, 0.35569084]],

       [[0.32596767, 0.38129556, 0.543151  ],
        [0.3083381 , 0.37968117, 0.5255565 ],
        [0.28617907, 0.37390995, 0.5035436 ],
        [0.2650344 , 0.37157938, 0.48360917],
        [0.24477842, 0.36640838, 0.46503332]],

       [[0.3719486 , 0.51681346, 0.82682395],
        [0.3812827 , 0.5280404 , 0.84833026],
        [0.39199868, 0.53916025, 0.86898583],
        [0.40028885, 0.54713225, 0.89229596],
        [0.40860504, 0.5569698 , 0.915524  ]],

       ...,

       [[0.64967686, 0.45145953, 0.27057105],
        [0.63391745, 0.45013216, 0.2668281 ],
        [0.6151396 , 0.44511327, 0.26162127],
        [0.5966431 , 0.4428497 , 0.2546297 ],
        [0.5784308 , 0.43946677, 0.24967419]],

       [[0.13535514, 0.20109624, 0.1956861 ],
        [0.12

In [352]:
testPredict

array([[[ 0.20810771,  0.3170994 ,  0.21010795],
        [ 0.15785792,  0.287397  ,  0.18189004],
        [ 0.10733083,  0.2305274 ,  0.14428048],
        [ 0.06348946,  0.15516613,  0.10123472],
        [ 0.01858404,  0.09150603,  0.0601626 ]],

       [[ 0.20215887,  0.14223874,  0.13712987],
        [ 0.18346247,  0.05465842,  0.09190805],
        [ 0.14470562,  0.00516413,  0.05892244],
        [ 0.09797475, -0.02066202,  0.03145142],
        [ 0.06135344, -0.04041574,  0.00968754]],

       [[ 0.80720955,  0.86552   ,  0.7852471 ],
        [ 0.8165108 ,  0.9120202 ,  0.80684996],
        [ 0.8561595 ,  0.97077477,  0.8575176 ],
        [ 0.9074799 ,  1.0015599 ,  0.9005967 ],
        [ 0.9536289 ,  1.0296293 ,  0.9390717 ]],

       ...,

       [[ 0.58784556,  0.6322715 ,  0.53461295],
        [ 0.70575345,  0.7070828 ,  0.61532605],
        [ 0.8001411 ,  0.77574825,  0.68204486],
        [ 0.8736629 ,  0.8574477 ,  0.746202  ],
        [ 0.9257079 ,  0.9463121 ,  0.8077583 ]],


In [576]:

trainPredict = np.reshape(trainPredict_final,(-1, 3))
trainPredict = scaler.inverse_transform(trainPredict)
trainPredict = np.reshape(trainPredict, (trainPredict_final.shape[0], 5, 3))





trainY = np.reshape(y_train,(-1, 3))
trainY = scaler.inverse_transform(trainY)
trainY = np.reshape(trainY, (y_train.shape[0], 5, 3))


testPredict = np.reshape(testPredict_final,(-1, 3))

testPredict = scaler.inverse_transform(testPredict)

testPredict = np.reshape(testPredict, (testPredict_final.shape[0], 5, 3))

# testY = scaler.inverse_transform(y_test)




testY = np.reshape(y_test,(-1, 3))
testY = scaler.inverse_transform(testY)
testY = np.reshape(testY, (y_test.shape[0], 5, 3))

In [587]:
import math
from sklearn.metrics import mean_squared_error

trainScore = math.sqrt(mean_squared_error(trainY[0:], trainPredict[0:]))
print('Train Score: %.2f RMSE' % (trainScore))
testScore = math.sqrt(mean_squared_error(testY, testPredict))
print('Test Score: %.2f RMSE' % (testScore))

700

In [596]:
y_new = scaler.fit_transform([[  100,   1,   1],
       [  95,   1,   1],
       [ 90,   1,   1],
       [ 85,   1,   1],
       [ 80,   1,   1],
       [ 75,   1,   1],
       [ 70,   1,   1],
       [ 65,   1,   1],
       [ 60,   1,   1],
       [ 55,   1,   1],
       [ 50,   1,   1],
       [ 45,   1,   1],
       [ 40,   1,   1],
       [ 35,   1,   1],
       [ 30,   1,   1]])

In [597]:

# input = keras.preprocessing.sequence.pad_sequences([[  16.45804213,   15.22674803,  421.3679909 ],
#        [  25.69521551,   15.59178985,  485.91398398],
#        [  32.85040243,   32.69030608,  981.69952713],
#        [  38.50750021,   40.35122778, 1027.83537699],
#        [  49.15993022,   42.1613794 , 1342.69331204],
#        [  61.35052901,   43.00845395, 1561.06022516],
#        [  62.38931938,   61.20173446, 1818.21389825],
#        [  70.11458945,   61.88013684, 1899.76126092],
#        [  74.57335295,   77.42281882, 2094.50162743],
#        [  75.44818747,   77.98237104, 2250.63550946]], maxlen=20)

x_input = array([y_new])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input)
print(yhat)
asd = np.reshape(yhat,(-1, 3))
asd = scaler.inverse_transform(asd)
asd = np.reshape(asd, (1, 5, 3))

asd

[[[ 0.08747833  0.10326362  0.10317092]
  [ 0.06332159  0.09383879  0.10410851]
  [ 0.03343333  0.05777171  0.08696106]
  [ 0.00584853  0.04511337  0.07098816]
  [-0.0080127   0.02676827  0.07797454]]]


array([[[36.12348  ,  1.1032636,  1.1031709],
        [34.43251  ,  1.0938388,  1.1041086],
        [32.340332 ,  1.0577717,  1.086961 ],
        [30.409397 ,  1.0451133,  1.0709882],
        [29.43911  ,  1.0267682,  1.0779746]]], dtype=float32)

In [530]:
y_new

array([[0.        , 0.        , 0.        ],
       [0.07142857, 0.        , 0.        ],
       [0.14285714, 0.        , 0.        ],
       [0.21428571, 0.        , 0.        ],
       [0.28571429, 0.        , 0.        ],
       [0.35714286, 0.        , 0.        ],
       [0.42857143, 0.        , 0.        ],
       [0.5       , 0.        , 0.        ],
       [0.57142857, 0.        , 0.        ],
       [0.64285714, 0.        , 0.        ],
       [0.71428571, 0.        , 0.        ],
       [0.78571429, 0.        , 0.        ],
       [0.85714286, 0.        , 0.        ],
       [0.92857143, 0.        , 0.        ],
       [1.        , 0.        , 0.        ]])

In [391]:
def AP(a,d,n): 

    # Printing AP by simply adding d 
    # to previous term. 
    curr_term = a 
    ap = []

    for i in range(1,n+1): 
        ap.append(curr_term)
        curr_term =curr_term + d 
    
    return ap
           
  
# Driver code 
a = 2    # starting number 
d = 2    # Common difference 
n = 5    # N th term to be find 
  
printAP(a, d, n) 

[2, 4, 6, 8, 10]

In [540]:
import os
import pandas as pd
import random
import numpy as np
def generate_data(tatal_sample, num_obs_min,num_obs_max, slope_min_range, slope_max_range,std):
    observations = {}
    oberserved_data = []
    target = []
    for per_example in range(tatal_sample):
        
        n = random.randrange(num_obs_min,num_obs_max)
        target_number = n+5
        std = std
#         slope = random.randrange(slope_min_range,slope_max_range)
#         slope1 =  random.randrange(slope_min_range,slope_max_range)
#         b = np.random.randn(target_number)*std
        
        x_intial_number = random.randrange(2,200)
        y_initial_number = random.randrange(2,200)
        z_initial_number = random.randrange(2,200)
        x_diff = random.randrange(1,10)
        y_diff = random.randrange(1,10)
        z_diff = random.randrange(1,10)
        x = AP(x_intial_number,x_diff,target_number)
        y = AP(y_initial_number,y_diff,target_number)
        z = AP(z_initial_number,z_diff,target_number)
        print(x)
        print(y)
        print(z)
        sort_type = random.choice([1,2])
#         sort_type = 1
        print(sort_type)
        if sort_type == 1:
            pass
        else:
            x = x[::-1]
            y = y[::-1]
            z = z[::-1]
        oberserved_data.append([[x[i],y[i],z[i]] for i in range(n)])
        target.append([[x[i],y[i],z[i]] for i in range(n,target_number)])
    observations['fly_position'] = oberserved_data
    observations['target'] = target
    data = pd.DataFrame(observations)
    data.to_csv(os.getcwd()+"/fly_position.csv")
    return oberserved_data,target

In [541]:
data_final,observations = generate_data(1000,10,15,10,20,50)

[170, 174, 178, 182, 186, 190, 194, 198, 202, 206, 210, 214, 218, 222, 226, 230, 234, 238, 242]
[154, 160, 166, 172, 178, 184, 190, 196, 202, 208, 214, 220, 226, 232, 238, 244, 250, 256, 262]
[51, 58, 65, 72, 79, 86, 93, 100, 107, 114, 121, 128, 135, 142, 149, 156, 163, 170, 177]
2
[2, 10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90, 98, 106, 114]
[114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128]
[124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152]
2
[31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96, 101]
[91, 96, 101, 106, 111, 116, 121, 126, 131, 136, 141, 146, 151, 156, 161]
[158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186]
2
[89, 92, 95, 98, 101, 104, 107, 110, 113, 116, 119, 122, 125, 128, 131]
[123, 130, 137, 144, 151, 158, 165, 172, 179, 186, 193, 200, 207, 214, 221]
[70, 79, 88, 97, 106, 115, 124, 133, 142, 151, 160, 169, 178, 187, 196]
1
[26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68]
[38,

[82, 86, 90, 94, 98, 102, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146]
[98, 102, 106, 110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154, 158, 162]
[169, 178, 187, 196, 205, 214, 223, 232, 241, 250, 259, 268, 277, 286, 295, 304, 313]
1
[151, 155, 159, 163, 167, 171, 175, 179, 183, 187, 191, 195, 199, 203, 207, 211, 215]
[79, 85, 91, 97, 103, 109, 115, 121, 127, 133, 139, 145, 151, 157, 163, 169, 175]
[95, 99, 103, 107, 111, 115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155, 159]
2
[194, 198, 202, 206, 210, 214, 218, 222, 226, 230, 234, 238, 242, 246, 250, 254, 258, 262]
[195, 199, 203, 207, 211, 215, 219, 223, 227, 231, 235, 239, 243, 247, 251, 255, 259, 263]
[184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201]
2
[180, 187, 194, 201, 208, 215, 222, 229, 236, 243, 250, 257, 264, 271, 278, 285, 292]
[153, 161, 169, 177, 185, 193, 201, 209, 217, 225, 233, 241, 249, 257, 265, 273, 281]
[37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 

In [557]:
X[2]

array([[  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [  0,   0,   0],
       [101, 161, 186],
       [ 96, 156, 184],
       [ 91, 151, 182],
       [ 86, 146, 180],
       [ 81, 141, 178],
       [ 76, 136, 176],
       [ 71, 131, 174],
       [ 66, 126, 172],
       [ 61, 121, 170],
       [ 56, 116, 168]], dtype=int32)

In [ ]:
learning_rate = 0.0001    
nepoch = 25               
T = 50                   # length of sequence
hidden_dim = 100         
output_dim = 1

bptt_truncate = 5
min_clip_value = -10
max_clip_value = 10

In [ ]:
U = np.random.uniform(0, 1, (hidden_dim, T))
W = np.random.uniform(0, 1, (hidden_dim, hidden_dim))
V = np.random.uniform(0, 1, (output_dim, hidden_dim))

In [556]:
model.save("RNN_model.h5")
print("Saved model to disk")

Saved model to disk


In [593]:
scorrers = model.evaluate(X_test, y_test, verbose = 0)

In [594]:
scorrers

2.3026776737727535e-05

In [595]:
model.summary()

Model: "sequential_63"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_29 (SimpleRNN)    (None, 200)               40800     
_________________________________________________________________
repeat_vector_25 (RepeatVect (None, 5, 200)            0         
_________________________________________________________________
simple_rnn_30 (SimpleRNN)    (None, 5, 200)            80200     
_________________________________________________________________
time_distributed_25 (TimeDis (None, 5, 3)              603       
Total params: 121,603
Trainable params: 121,603
Non-trainable params: 0
_________________________________________________________________
